CREATE TABLE IF NOT EXISTS `users` (
    `id`  INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(100) NOT NULL,
    `password` VARCHAR(100) NOT NULL
)
  ENGINE = INNODB
  DEFAULT CHARACTER SET utf8;

  CREATE TABLE IF NOT EXISTS `genres` (
    `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL
)
  ENGINE = INNODB
  DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `films` (
    `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `description` TEXT NOT NULL,
    `country` VARCHAR(100) NOT NULL,
    `quality` VARCHAR(100) NOT NULL
)
  ENGINE = INNODB
  DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `film_genres` (
  film_id INT NOT NULL,
  genre_id INT NOT NULL,

  FOREIGN KEY (film_id) REFERENCES `films` (id),
  FOREIGN KEY (genre_id) REFERENCES `genres` (id),

  UNIQUE (film_id, genre_id)
)